epollchain/chain/routes.py
# -*- coding: utf-8 -*-
"""
Created on Sun Jan 26 23:20:06 2020

@author: yashm
"""

import functools
from flask_bcrypt import Bcrypt
from flask import Blueprint
from flask import flash
from flask import g
from flask import redirect
from flask import render_template
from flask import request
from flask import session
from flask import url_for
from werkzeug.security import check_password_hash
from werkzeug.security import generate_password_hash
import datetime
import hashlib
import json
from flask import Flask, jsonify, request
from uuid import uuid4
from urllib.parse import urlparse
import requests
from flask_login import login_user, current_user, logout_user, login_required, LoginManager
from epollchain.chain.blockchain import (Blockchain,PollForm,VoteForm)
 

chain = Blueprint('chain', __name__,url_prefix='/')

#bp = Blueprint('chain', __name__, url_prefix='/chain')

@chain.url_defaults
def bp_url_defaults(endpoint, values):
    url_prefix = getattr(g, 'url_prefix', None)
    if url_prefix is not None:
        values.setdefault('url_prefix', url_prefix)

@chain.url_value_preprocessor
def bp_url_value_preprocessor(endpoint, values):
    g.url_prefix = values.pop('url_prefix')
    
    

# Creating an address for the node on Port 5000
node_address = str(uuid4()).replace('-', '')

# Creating a Blockchain
blockchain = Blockchain()

#Create bcrypt object
bcrypt = Bcrypt()


@chain.route('/get_chain', methods = ['GET'])
def get_chain():
    response = {'chain': blockchain.chain,'length': len(blockchain.chain)}
    return jsonify(response),200#jsonify(response), 200


@chain.route('/show_chain', methods = ['GET'])
@login_required
def show_chain():
    replace_chain = blockchain.replace_chain()
    is_valid = blockchain.is_chain_valid(blockchain.chain)
    print('valddd',is_valid)
    if is_valid and replace_chain:
        valid = 'Replaced and Validated'
    elif is_valid and not replace_chain:
        valid = 'Validated'
    else:
        valid = 'Invalid'
        
    return render_template('show_chain.html',res_chain=blockchain.chain,valid=valid)#jsonify(response), 200

# Connecting new nodes
@chain.route('/home', methods = ['GET'])
@login_required
def connect_node():
    with open('epollchain/data/personal.json') as file:
        personal = json.load(file)
        personal['privatekey']=blockchain.hash(personal)
        personal['publickey']=blockchain.hash(personal['privatekey'])
    print(request.host_url)
    with open('epollchain/data/nodes.json') as file:
        nodes = json.load(file)
    if nodes == {}:
         nodes = {'message': 'Not connected.'}
    else:
        for node in nodes:
            try:
                print (f'http://{node}/isactive')
                if ((requests.get(f'http://{node}/isactive')).json()["status"] == "Active"):
                    blockchain.add_node(node)
                    requests.post(f'http://{node}/isactive',json={request.host_url:""})
            except:
                print("fail to connect")
        if len(blockchain.nodes)>0:
            nodes = {'message': 'All the nodes are now connected.','total_nodes': list(blockchain.nodes)}
        else :
            nodes = {'message': 'Not connected.'}

    return render_template('home.html',res_personal = personal, res_nodes = nodes)
                           
@chain.route('/isactive', methods = ['GET'])
def is_active():
    return jsonify({"status":blockchain.active}),200

@chain.route('/gettransaction', methods = ['GET'])
def gettransaction():
    if blockchain.transactions:
        return jsonify(blockchain.transactions,200)
    else:
        return jsonify({}),200

@chain.route('/isactive', methods = ['POST'])
def active_add():
    parsed_url = urlparse(request.get_json())
    print(parsed_url.netloc)
    with open('epollchain/data/nodes.json','w+') as outfile:
        json.dump(parsed_url.netloc, outfile)
    return "Added",200

@chain.route("/poll/new", methods=['GET', 'POST'])
@login_required
def new_poll():
    form = PollForm()
    print (current_user.email)
    if form.validate_on_submit():
        index = blockchain.add_transaction(form.title.data, form.content.data,current_user.email, str(datetime.datetime.now()),None,None,None)
        print (index,blockchain.transactions)
        flash('Your poll has been created!', 'success')
        return redirect('/mine')
    return render_template('create_poll.html', title='New Poll',
                           form=form, legend='New Poll')

@chain.route("/polls", methods=['GET', 'POST'])
def polls():
    replace_chain = blockchain.replace_chain()
    is_valid = blockchain.is_chain_valid(blockchain.chain)
    transaction_polls=[]
    for transaction in blockchain.chain:
        print(transaction)
        if transaction['index']>1:
            if transaction['transactions']['vote']==None:
                transaction_polls.append(transaction['transactions'])
    return render_template('polls.html', transactions = transaction_polls)#return render_template('home.html', posts=posts)

@chain.route("/vote/<string:poll_id>", methods=['GET', 'POST'])
def vote(poll_id):
    pollvote={}
    form = VoteForm()
    for transaction in blockchain.chain:
        if transaction['index']>1 and str(poll_id)== str(transaction['transactions']['transaction_id']):
            pollvote=transaction['transactions']
    if request.method == 'POST' or form.validate_on_submit():
        print ('aaaaa',form.transaction_detail.data)
        index = blockchain.add_transaction(pollvote['question_title'], pollvote['question'],pollvote['posted_by'],pollvote['time_posted'],form.vote_value.data,current_user.email,str(datetime.datetime.now()))
        print (index,form.vote_value.data)
        flash('Your poll has been created!', 'success')
        return redirect('/polls')
    elif request.method == 'GET':
        form.transaction_detail = pollvote
    return render_template('vote.html', pollvote = pollvote,form = form)


@chain.route("mine", methods=['GET'])
def mine():
    with open('epollchain/data/nodes.json') as file:
        nodes = json.load(file)
    if nodes == {}:
         nodes = {'message': 'Not connected.'}
    else:
        for node in nodes:
            try:
                if ((requests.get(f'http://{node}/gettransaction')).json()):
                    new_t = (requests.get(f'http://{node}/gettransaction')).json()
                    print (new_t[0])
                    for transaction in new_t[0]:
                        for local_transaction in blockchain.transactions:
                            if not(transaction['transaction_id']==local_transaction['transaction_id']):
                                blockchain.transactions.append(transaction)
            except requests.ConnectionError:
                print("fail to connect")
    return render_template('mine.html', transactions = blockchain.transactions)

@chain.route("/mine/<string:transaction_id>", methods=['GET', 'POST'])
def block(transaction_id):
    previous_block = blockchain.get_previous_block()
    previous_proof = previous_block['proof']
    proof = blockchain.proof_of_work(previous_proof)
    previous_hash = blockchain.hash(previous_block)
    block = blockchain.create_block(proof, previous_hash,transaction_id)
    print(block)
    flash('Your block has been created!', 'success')
    return render_template('mine.html', transactions = blockchain.transactions)

epollchain/users/routes.py
# -*- coding: utf-8 -*-
"""
Created on Sun Feb  2 22:33:34 2020

@author: yashm
"""
from flask import current_app as app
import secrets
import os
from PIL import Image
import json
from flask import render_template, url_for, flash, redirect, request, Blueprint
from flask_login import login_user, current_user, logout_user, login_required
from epollchain import bcrypt # db
from epollchain.models import User#, Post
from epollchain.users.forms import (RegistrationForm, LoginForm , UpdateAccountForm)#,RequestResetForm, ResetPasswordForm)
#from Blockvote.users.utils import save_picture, send_reset_email

users = Blueprint('users', __name__)
user = User()


def save_picture(form_picture):
    random_hex = secrets.token_hex(8)
    _, f_ext = os.path.splitext(form_picture.filename)
    picture_fn = random_hex + f_ext
    picture_path = os.path.join(app.root_path, 'static\profile_pics', picture_fn)
 #   form_picture.save(picture_path)
    output_size = (125, 125)
    i = Image.open(form_picture)
    i.thumbnail(output_size)
    i.save(picture_path)

    return picture_fn

@users.route("/register", methods=['GET', 'POST'])
def register():
    if current_user.is_authenticated:
        return redirect('/home')
    form = RegistrationForm()
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        personal = {}
        personal['name'] = form.username.data
        personal['password']=hashed_password
        personal['emailid']=form.email.data
        with open('epollchain/data/personal.json','w') as outfile:
            json.dump(personal, outfile)#json.dumps(data)
        flash(f'Account created for {form.username.data}!', 'success')
        return redirect(url_for('users.login'))
    return render_template('register.html', title='Register', form=form)


@users.route("/login", methods=['GET', 'POST'])
def login():
    if current_user.is_authenticated:
        return redirect('/home')  
    form = LoginForm()
    with open('epollchain/data/personal.json') as file:
        personal = json.load(file)
    if form.validate_on_submit():
        if form.email.data == personal['emailid'] and bcrypt.check_password_hash(personal['password'], form.password.data):
            flash('You have been logged in!', 'success')
            login_user(user, remember=form.remember.data)
            next_page = request.args.get('next')
            return redirect(next_page) if next_page else redirect('/home')
        else:
            flash('Login Unsuccessful. Please check email and password', 'danger')
    return render_template('login.html', title='Login', form=form)

@users.route("/logout")
def logout():
    logout_user()
    return redirect('/login')


@users.route("/account",methods=['GET', 'POST'])
@login_required
def account():
    form = UpdateAccountForm()
    if form.validate_on_submit():
        if form.picture.data:
            picture_file = save_picture(form.picture.data)
            current_user.image_file = picture_file
        current_user.username = form.username.data
        current_user.email = form.email.data
       # db.session.commit()
        flash('Your account has been updated!', 'success')
        return redirect('/account')
    elif request.method == 'GET':
        form.username.data = current_user.username
        form.email.data = current_user.email
    image_file = url_for('static', filename='profile_pics/' + current_user.image_file)
    return render_template('account.html', title='Account',
                           image_file=image_file, form=form)

epollchain/templates/account.html
{% extends "base.html" %}
{% block content %}
    <div class="content-section">
      <div class="media">
        <img class="rounded-circle account-img" src="{{ image_file }}">
        <div class="media-body">
          <h2 class="account-heading">{{ current_user.username }}</h2>
          <p class="text-secondary">{{ current_user.email }}</p>
        </div>
      </div>
        <form method="POST" action="" enctype="multipart/form-data">
            {{ form.hidden_tag() }}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Account Info</legend>
                <div class="form-group">
                    {{ form.username.label(class="form-control-label") }}

                    {% if form.username.errors %}
                        {{ form.username(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.username.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.username(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.email.label(class="form-control-label") }}
                    {% if form.email.errors %}
                        {{ form.email(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.email.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.email(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.picture.label() }}
                    {{ form.picture(class="form-control-file") }}
                    {% if form.picture.errors %}
                        {% for error in form.picture.errors %}
                            <span class="text-danger">{{ error }}</span></br>
                        {% endfor %}
                    {% endif %}
                </div>
            </fieldset>
            <div class="form-group">
                {{ form.submit(class="btn btn-outline-info") }}
            </div>
        </form>
    </div>
{% endblock content %}

epollchain/templates/base.html
<!DOCTYPE html>
<html>
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='main.css') }}">

    {% if title %}
        <title>epollchain - {{ title }}</title>
    {% else %}
        <title>epollchain</title>
    {% endif %}
</head>
<body>
    <header class="site-header">
      <nav class="navbar navbar-expand-md navbar-dark bg-steel fixed-top">
        <div class="container">
          <a class="navbar-brand mr-4" href="/home">epollchain</a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle" aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarToggle">
            <div class="navbar-nav mr-auto">
              <a class="nav-item nav-link" href="/home">Home</a>
              <a class="nav-item nav-link" href="{{ url_for('chain.show_chain') }}">Chain</a>
              <a class="nav-item nav-link" href="/poll/new">Create</a>
              <a class="nav-item nav-link" href="/polls">Vote</a>
              <a class="nav-item nav-link" href="/mine">Mine</a>
            </div>
            <!-- Navbar Right Side -->

            
            <div class="navbar-nav">
              {% if current_user.is_authenticated %}
                <a class="nav-item nav-link" href="/logout">Logout</a>
                <a class="nav-item nav-link" href="/account">Account</a>
              {% else %}
                <a class="nav-item nav-link" href="/login">Login</a>
                <a class="nav-item nav-link" href="/register">Register</a>
              {% endif %}
            </div>
          </div>
        </div>
      </nav>
    </header>
    <main role="main" class="container">
      <div class="row">
        <div class="col-md-8">
          {% with messages = get_flashed_messages(with_categories=true) %}
            {% if messages %}
              {% for category, message in messages %}
                <div class="alert alert-{{ category }}">
                  {{ message }}
                </div>
              {% endfor %}
            {% endif %}
          {% endwith %}

          {% block content %}{% endblock %}

        </div>
        <div class="col-md-4">
          <div class="content-section">
            <h3>Our Sidebar</h3>
            <p class='text-muted'>You can put any information here you'd like.
              <ul class="list-group">
                <li class="list-group-item list-group-item-light">Latest Posts</li>
                <li class="list-group-item list-group-item-light">Announcements</li>
                <li class="list-group-item list-group-item-light">Calendars</li>
                <li class="list-group-item list-group-item-light">etc</li>
              </ul>
            </p>
          </div>
        </div>
      </div>
    </main>


    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
</body>
</html>

epollchain/templates/create_poll.html
{% extends "base.html" %}
{% block content %}
<div class="content-section">
    <form method="POST" action="">
        {{ form.hidden_tag() }}
        <fieldset class="form-group">
            <legend class="border-bottom mb-4">{{ legend }}</legend>
            <div class="form-group">
                {{ form.title.label(class="form-control-label") }}
                {% if form.title.errors %}
                    {{ form.title(class="form-control form-control-lg is-invalid") }}
                    <div class="invalid-feedback">
                        {% for error in form.title.errors %}
                            <span>{{ error }}</span>
                        {% endfor %}
                    </div>
                {% else %}
                    {{ form.title(class="form-control form-control-lg") }}
                {% endif %}
            </div>
            <div class="form-group">
                {{ form.content.label(class="form-control-label") }}
                {% if form.content.errors %}
                    {{ form.content(class="form-control form-control-lg is-invalid") }}
                    <div class="invalid-feedback">
                        {% for error in form.content.errors %}
                            <span>{{ error }}</span>
                        {% endfor %}
                    </div>
                {% else %}
                    {{ form.content(class="form-control form-control-lg") }}
                {% endif %}
            </div>
        </fieldset>
        <div class="form-group">
            {{ form.submit(class="btn btn-outline-info") }}
        </div>
    </form>
</div>
{% endblock content %}

epollchain/templates/home.html
{% extends 'base.html' %}
{% block content %}
<div><h1>Welcome , {{ res_personal.name }}</h1></div>
<br>    
<div><p>Email ID - {{ res_personal.emailid }}</p></div>
<div><p>Private Key - {{ res_personal.privatekey }}</p></div>
<div><p>Public Key - {{ res_personal.publickey }}</p></div>
<div><p>Status - {{ res_nodes.message }}</p></div>
{% if res_nodes.total_nodes %}
<div><p>Node list - {{ res_nodes.total_nodes }}</p></div>
{% else %}
<div><p>Node list - Empty {{ res_nodes.total_nodes }}</p></div>
{% endif %}
{% endblock content %}

epollchain/templates/login.html
{% extends 'base.html' %}
{% block content %}
    <div class="content-section">
        <form method="POST" action="">
            {{ form.hidden_tag() }}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Log In</legend>
                <div class="form-group">
                    {{ form.email.label(class="form-control-label") }}
                    {% if form.email.errors %}
                        {{ form.email(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.email.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.email(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.password.label(class="form-control-label") }}
                    {% if form.password.errors %}
                        {{ form.password(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.password.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.password(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-check">
                    {{ form.remember(class="form-check-input") }}
                    {{ form.remember.label(class="form-check-label") }}
                </div>
            </fieldset>
            <div class="form-group">
                {{ form.submit(class="btn btn-outline-info") }}
            </div>
            <small class="text-muted ml-2">
                <a href="#">Forgot Password?</a>
            </small>
        </form>
    </div>
    <div class="border-top pt-3">
        <small class="text-muted">
            Need An Account? <a class="ml-2" href="{{ url_for('users.register') }}">Sign Up Now</a>
        </small>
    </div>
{% endblock content %}

epollchain/templates/mine.html
{% extends "base.html" %}
{% block content %}
    {% for poll in transactions %}
        <article class="media content-section">
          <img class="rounded-circle article-img" src="{{ url_for('static', filename='profile_pics/' + 'profile.jpg' )}}">
          <div class="media-body">
            <div class="article-metadata">
              <a class="mr-2" href="#">{{ poll.posted_by }}</a>
              <small class="text-muted">{{ poll.time_posted }}</small>
            </div>
            <p class="article-title"><kbd >Title:-</kbd> {{ poll.question_title }} <a href="/mine/{{poll.transaction_id}}" class="btn btn-outline-info mt-2 float-right ">Mine</a></p>
            <p class="article-content"><kbd >Question :-</kbd> {{ poll.question }}</p>
            <p class="article-content"><kbd >Vote :-</kbd> {{ poll.vote }}</p>
            <p class="article-content"><kbd >Voted By :-</kbd> {{ poll.voter }}</p>
            <p class="article-content"><kbd >Voted on  :-</kbd> {{ poll.time_voted }}</p>
          </div>
        </article>
    {% endfor %}
{% endblock content %}

epollchain/templates/polls.html
{% extends "base.html" %}
{% block content %}
    {% for poll in transactions %}
        <article class="media content-section">
          <img class="rounded-circle article-img" src="{{ url_for('static', filename='profile_pics/' + 'profile.jpg' )}}">
          <div class="media-body">
            <div class="article-metadata">
              <a class="mr-2" href="#">{{ poll.posted_by }}</a>
              <small class="text-muted">{{ poll.time_posted }}</small>
            </div>
            <h2><p class="article-title">{{ poll.question_title }} <a href="/vote/{{poll.transaction_id}}" class="btn btn-outline-info mt-2 float-right ">Vote</a></p></h2>
            <p class="article-content">{{ poll.question }}</p>
          </div>
        </article>
    {% endfor %}
{% endblock content %}

epollchain/templates/register.html
{% extends 'base.html' %}
{% block content %}
    <div class="content-section">
        <form method="POST" action="">
            {{ form.hidden_tag() }}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Join Today</legend>
                <div class="form-group">
                    {{ form.username.label(class="form-control-label") }}

                    {% if form.username.errors %}
                        {{ form.username(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.username.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.username(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.email.label(class="form-control-label") }}
                    {% if form.email.errors %}
                        {{ form.email(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.email.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.email(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.password.label(class="form-control-label") }}
                    {% if form.password.errors %}
                        {{ form.password(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.password.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.password(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.confirm_password.label(class="form-control-label") }}
                    {% if form.confirm_password.errors %}
                        {{ form.confirm_password(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.confirm_password.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.confirm_password(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
            </fieldset>
            <div class="form-group">
                {{ form.submit(class="btn btn-outline-info") }}
            </div>
        </form>
    </div>
    <div class="border-top pt-3">
        <small class="text-muted">
            Already Have An Account? <a class="ml-2" href="/login">Sign In</a>
        </small>
    </div>
{% endblock content %}

epollchain/templates/show_chain.html
{% extends 'base.html' %}


{% block content %}
<div><h1>Current Chain ({{valid}})</h1></div>
    {% for res in res_chain %}
        <article class="media content-section">
          <div class="media-body">
            <p class="article-content">{{ res }}</p>
          </div>
        </article>
    {% endfor %}
{% endblock content %}

epollchain/templates/vote.html
{% extends 'base.html' %}

{% block content %}
  <article class="media content-section">
    <img class="rounded-circle article-img" src="{{ url_for('static', filename='profile_pics/' + 'profile.jpg') }}">
    <div class="media-body">
      <div class="article-metadata">
        <a class="mr-2" href="#">{{ pollvote.posted_by }}</a>
        <small class="text-muted">{{ pollvote.time_posted}}</small>
      </div>
      <h2 class="article-title">{{ pollvote.question_title }}</h2>
      <p class="article-content">{{ pollvote.question }}</p>
    </div>
  </article>
 <!-- Modal -->
 <div class="content-section">
  <form method="POST" action="" enctype="multipart/form-data">
    {{ form.hidden_tag() }}
      <fieldset class="form-group">
          <legend class="border-bottom mb-4">Please vote </legend>
          <div class="input-group-prepend">
              {{ form.vote_value(class="radio-inline list-inline list-group-horizontal") }}

          </div>
          
      </fieldset>
      <div class="form-group">
        {{ form.submit(class="btn btn-outline-info") }}
    </div>
  </form>
</div>
{% endblock content %}